config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: [:show, :new, :create, :destroy]
  resources :runs
  resources :brands
  resources :shoes
  resources :runners
  resources :runner_shoes, only: [:show, :new, :create, :destroy]

  root "welcome#homepage"
  get 'terms-and-conditions', to: 'welcome#terms'
  get 'privacy-policy', to: 'welcome#privacy'
  get 'support', to: 'welcome#support'
  get 'about-us', to: 'welcome#about'
  get 'features', to: 'welcome#features'
  get 'contact-us', to: 'welcome#contact'
  get 'what-is-rails-runner', to: 'welcome#whatis'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#process_login'
  get 'logout', to: 'sessions#logout'
  get 'runner/:id/my_runs', to: 'runners#my_runs', as: 'my_runs'
  get 'runner/:id/my_shoes', to: 'runners#my_shoes', as: 'my_shoes'
  get 'brand/:id/targeting', to: 'brands#targeting', as: 'targeting'
  get 'brand/:id/loyal_customers', to: 'brands#loyal_customers', as: 'loyal'

end

app/models/admin.rb
class Admin < ApplicationRecord
    has_one :user, as: :profileable
    accepts_nested_attributes_for :user
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :shoes
    has_one :user, as: :profileable

    validates :name, presence: true, length: { minimum: 3 }

    #ANALYTICS
    def due_for_new_pair?
        runner_array = [] 
        self.shoes.each do |shoe|
            shoe.runner_shoes.each do |runner_shoe|
                if runner_shoe.get_miles.to_i > 250
                    runner_array << runner_shoe.runner 
                end 
            end
        end
        return runner_array.uniq
    end

    def loyal_customers
        loyal_customers = []
        Runner.all.each do |runner|
            brand_array = runner.shoes.map {|shoe| shoe.brand}
            if brand_array.count(self) > 1
                loyal_customers << runner
            end
        end
        return loyal_customers
    end

end

app/models/run.rb
class Run < ApplicationRecord
    belongs_to :runner
    belongs_to :runner_shoe

    validates :date, presence: true
    validates :distance, presence: true
    validates :time, presence: true

    def run_location_and_date
        return "#{self.location} -- #{self.date.strftime('%m/%d/%Y')}"
    end

    def location_date_distance
        return "#{self.location} -- #{self.distance} #{'mile'.pluralize(self.distance)} -- #{self.date.strftime('%m/%d')}"
    end

    def format_time
        seconds = self.time % 60
        minutes = (self.time / 60) % 60
        hours = self.time / (60 * 60)
        # return "#{hours}:#{minutes}:#{seconds}"
        format("%02d:%02d:%02d", hours, minutes, seconds)
    end

end

app/models/runner.rb
class Runner < ApplicationRecord
    has_many :runs
    has_many :runner_shoes
    has_many :shoes, through: :runner_shoes
    has_one :user, as: :profileable
    accepts_nested_attributes_for :user

    validates :name, presence: true
    validates :age, allow_nil: true, numericality: {only_integer: true, minimum: 1}
    validate :validates_shoe_size

    def get_miles
        total_distance = self.runs.map {|run| run.distance}
        total_distance_sum = total_distance.sum.round(2)
        return "#{total_distance_sum} #{'mile'.pluralize(total_distance_sum)}"
    end

    def total_runs
        self.runs.count
    end

    def sort_runs
       self.runs.sort_by{|run|run.date}.reverse!
    end


    private

    def validates_shoe_size
        shoe_size.nil? || (shoe_size - shoe_size.to_i == 0.5) || (shoe_size - shoe_size.to_i == 0)
    end


end

app/models/runner_shoe.rb
class RunnerShoe < ApplicationRecord
    belongs_to :runner 
    belongs_to :shoe 
    has_many :runs

    validates :runner, presence: true, length: { minimum: 2 }
    validates :shoe, presence: true, length: { minimum: 2 }

    def brand_with_name
        return "#{self.shoe.brand.name} #{self.shoe.name}"
    end

    def get_miles
        total_distance = self.runs.map {|run| run.distance}
        total_distance_sum = total_distance.sum
        return "#{total_distance_sum} #{'mile'.pluralize(total_distance_sum)}"
    end
end

app/models/shoe.rb
class Shoe < ApplicationRecord
    has_one_attached :avatar
    
    belongs_to :brand
    has_many :runner_shoes
    has_many :runners, through: :runner_shoes

    def brand_with_name
        return "#{self.brand.name} #{self.name}"
    end

    def self.sorted_by_brand
        self.joins(:brand).merge(Brand.order(:name))
    end

    def self.get_all_runs(shoe_id)
        self.select(:'shoes.id', :'runs.runner_id', :'runs.distance').joins(runner_shoes: :runs).where(id: shoe_id)
    end

    def total_runs
        x = Shoe.get_all_runs(self.id).map do |run| 
            run.runner_id
        end.count
    end

    def total_miles
        Shoe.get_all_runs(self.id).map do |run| 
            run.distance
        end.sum
    end

    def average_miles_ran_per_run
        if self.total_runs > 0
            (self.total_miles / self.total_runs).round(2)
        else
            return 0
        end
    end

    def average_miles_ran_per_runner
        if self.total_runs > 0
            return (self.total_miles / self.runners.count).round(2)
        else 
            return 0
        end
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    belongs_to :profileable, polymorphic: true, optional: true
    validates :username, presence: true, uniqueness: true
    
    # POLYMORPHIC TYPE TESTS 
    def is_runner?
        self.profileable_type == 'Runner'
    end

    def is_brand?
        self.profileable_type == 'Brand'
    end

    def is_admin?
        self.profileable_type == 'Admin'
    end


end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
    before_action :set_run, only: [:show, :edit, :update, :destroy]
    
    def index
        @runs = Run.order(date: :desc)
    end

    def show
    end

    def new
        @run = Run.new
    end

    def create
        @run = Run.new(run_params)
        @run.time = time_converter(params[:time_attributes])
        if @run.save
            redirect_to run_path(@run)
        else 
            render :new
        end
    end

    def edit
    end

    def update
        if @run.update(run_params)
            redirect_to run_path(@run)
        else
            render :edit
        end
    end

    def destroy
        @runner = @run.runner
        @run.destroy
        redirect_to runner_path(@runner)
    end

    private

    def run_params
        params.require(:run).permit(:runner_id, :runner_shoe_id, :location, :date, :distance, :time)
    end

    def set_run
        @run = Run.find(params[:id])
    end

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
    before_action :set_shoe, only: [:show, :edit, :update, :destroy]
    
    def index
        @shoes = Shoe.all
    end

    def show
    end

    def new
        @shoe = Shoe.new
    end

    def create
        @shoe = Shoe.new(shoe_params)
        if @shoe.save
            redirect_to shoe_path(@shoe)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @shoe.update(shoe_params)
            redirect_to shoe_path(@shoe)
        else
            render :edit
        end
    end

    def destroy
        @brand = @shoe.brand
        @shoe.destroy
        redirect_to brand_path(@brand)
    end

    private

    def shoe_params
        params.require(:shoe).permit(:brand_id, :name, :price, :year, :avatar)
    end

    def set_shoe
        @shoe = Shoe.find(params[:id])
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/runner_shoes_helper.rb
module RunnerShoesHelper
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/new.html.erb
<%= bootstrap_form_for @admin do |f| %>
    <%= fields_for :user_attributes do |u| %>
        <div class="form-group">
            <%= u.label :username, class: 'required' %>
            <%= u.text_field :username, class: 'form-control' %>
            <%= u.label :password, class: 'required' %>
            <%= u.password_field :password, class: 'form-control' %>
            <%= u.label 'Confirm password', class: 'required' %>
            <%= u.password_field :password_confirmation, class: 'form-control' %>
        </div>
    <% end %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/admins/show.html.erb
<h1>Welcome <%= @admin.name %>!</h1>
<h3>Congrats on being an admin.</h3>
<br>
<br>
<p>Enjoy all the power!</p>

<div>
    <h5>Delete profile</h5>
    <%= link_to 'Click here to delete profile', admin_path(current_user.profileable.id), method: :delete, data: {confirm: "Are you sure?" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRunner</title>
    <link rel="icon" type="image/png" href="https://i.imgur.com/ASCAhAd.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= @homepage ? 'homepage' : 'pages'%>">
    <header>
      <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="/"><%= image_tag("logo.png", size:'150x40') %></a>
        <form class="form-inline">
          <% if logged_in? %>
            <a class="btn btn-outline-light" href=<%= logout_path %> role="button">Logout</a>
          <% else %>
            <a class="btn btn-outline-light" href=<%= new_runner_path %> role="button">Signup</a>
            <div style="padding-left: 10px;">
            <a class="btn btn-outline-light" href= <%= login_path %> role="button">Login</a>
          <% end %>
          </div>
        </form>
      </nav>
    </header>
    <% if logged_in? %>
    <div class="secondary_navbar">
        <% if logged_in_admin? %>
          <div class="navbar navbar-light bg-light">
            <ul class="nav">
              <li class="nav-item"><%= link_to "Runners", runners_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Shoes", shoes_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Brands", brands_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Runs", runs_path, class: "nav-link" %></li>
            </ul>
          </div>
        <% end %>
        <% if logged_in_runner? %>
          <div class="navbar navbar-light bg-light">
            <ul class="nav">
              <li class="nav-item"><%= link_to current_user.profileable.name, runner_path(current_user.profileable.id), class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "My Runs", my_runs_path(current_user.profileable.id), class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "My Shoes", my_shoes_path(current_user.profileable.id), class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "New Run", new_run_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "New Shoes", new_runner_shoe_path, class: "nav-link" %></li>
              <% if controller_name == "runners" && action_name == "show" %>
                <li class="nav-item"><%= link_to "Edit Profile", edit_runner_path(current_user.profileable.id), class: "nav-link" %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <% if logged_in_brand? %>
          <div class="navbar navbar-light bg-light">
            <ul class="nav">
              <li class="nav-item"><%= link_to current_user.profileable.name, brand_path(current_user.profileable.id), class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "New Shoe", new_shoe_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Targeting", targeting_path(current_user.profileable.id), class: "nav-link" %></li>
              <li class="nav-item"><%= link_to "Loyalty", loyal_path(current_user.profileable.id), class: "nav-link" %></li>
              <% if controller_name == "brands" && action_name == "show" %>
                <li class="nav-item"><%= link_to "Edit Profile", edit_brand_path(current_user.profileable.id), class: "nav-link" %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
    </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    <footer class="page-footer font-small footer-light pt-4">
      <!-- Footer Links -->
      <div class="container-fluid text-center text-md-left">
      <!-- Grid row -->
      <div class="row">
        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">
          <!-- Content -->
          <img src='/assets/logo-ed759e7e8e96637d799d8f80541a0354e5131652366a6e48f9f2ee6c22283f37.png' class='footer_logo'>
          <%# <%= image_tag("logo.png")  %><br><br>
          <p style="font-style: italic; width: 45%">We may not know how to do things the right way, but we're pretty good at doing them the wrong way!</p>
        </div>
        <!-- Grid column -->
        <hr class="clearfix w-100 d-md-none pb-3">
        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
          <!-- Links -->
          <h5 class="text-uppercase">Brands</h5>
          <ul class="list-unstyled">
            <li><%= link_to 'Add your brand', new_brand_path, class: 'footer-link' %></li>
            <li><%= link_to 'Support', support_path, class: 'footer-link' %></li>
            <li><%= link_to "Terms and conditions", terms_and_conditions_path, class: 'footer-link' %></li>
            <li><%= link_to "Privacy Policy", privacy_policy_path, class: 'footer-link' %></li>
          </ul>
        </div>
        <!-- Grid column -->
        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">
          <!-- Links -->
          <h5 class="text-uppercase">Users</h5>
          <ul class="list-unstyled">
          <li><%= link_to 'About Us', about_us_path, class: "footer-link" %></li>
          <li><%= link_to 'What is Rails Runner?', what_is_rails_runner_path, class: "footer-link" %></li>
          <li><%= link_to 'Features', features_path, class: "footer-link" %></li>
          <li><%= link_to 'Contact Us', contact_us_path, class: "footer-link" %></li>
        </ul>
      </div>
      <!-- Grid column -->
    </div>
    <!-- Grid row -->
  </div>
  <!-- Footer Links -->
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright: Andy Aguilar and Michael Jester
  </div>
  <!-- Copyright -->
</footer>
  </body>
</html>