config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: [:show, :new, :create, :destroy]
  resources :runs
  resources :brands
  resources :shoes
  resources :runners
  resources :runner_shoes, only: [:show, :new, :create, :destroy]

  root "welcome#homepage"
  get 'terms-and-conditions', to: 'welcome#terms'
  get 'privacy-policy', to: 'welcome#privacy'
  get 'support', to: 'welcome#support'
  get 'about-us', to: 'welcome#about'
  get 'features', to: 'welcome#features'
  get 'contact-us', to: 'welcome#contact'
  get 'what-is-rails-runner', to: 'welcome#whatis'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#process_login'
  get 'logout', to: 'sessions#logout'
  get 'runner/:id/my_runs', to: 'runners#my_runs', as: 'my_runs'
  get 'runner/:id/my_shoes', to: 'runners#my_shoes', as: 'my_shoes'
  get 'brand/:id/targeting', to: 'brands#targeting', as: 'targeting'
  get 'brand/:id/loyal_customers', to: 'brands#loyal_customers', as: 'loyal'

end

app/models/runner.rb
class Runner < ApplicationRecord
    has_many :runs
    has_many :runner_shoes
    has_many :shoes, through: :runner_shoes
    has_one :user, as: :profileable
    accepts_nested_attributes_for :user

    validates :name, presence: true
    validates :age, allow_nil: true, numericality: {only_integer: true, minimum: 1}
    validate :validates_shoe_size

    def get_miles
        total_distance = self.runs.map {|run| run.distance}
        total_distance_sum = total_distance.sum.round(2)
        return "#{total_distance_sum} #{'mile'.pluralize(total_distance_sum)}"
    end

    def total_runs
        self.runs.count
    end

    def sort_runs
       self.runs.sort_by{|run|run.date}.reverse!
    end


    private

    def validates_shoe_size
        shoe_size.nil? || (shoe_size - shoe_size.to_i == 0.5) || (shoe_size - shoe_size.to_i == 0)
    end


end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
    before_action :set_runner, only: [:show, :edit, :update, :destroy, :my_runs, :my_shoes]
    
    def index
        @runners = Runner.all
    end

    def show
    end

    def my_runs
        
    end

    def my_shoes
    end

    def new
        @runner = Runner.new
    end
    
    def create
        @runner = Runner.new(runner_params)
        @user = User.new(user_params)
        if @user.valid? && @runner.valid?
            @user.save
            @user.profileable = @runner
            @user.save
            session[:user_id] = @user.id
            redirect_to runner_path(@runner)
        else
            @runner.valid?
            @errors = @runner.errors.full_messages.concat(@user.errors.full_messages)
            render :new
        end
    end

    def edit
        @user = @runner.user
    end

    def update
        @user = @runner.user
        @user.username = params[:user][:username]
        if @runner.update(runner_params) && @user.save
            redirect_to runner_path(@runner)
        else
            render 'edit'
        end
    end

    def destroy
        @runner.user.destroy
        @runner.destroy
        redirect_to root_path
    end

    private

    def set_runner
        @runner = Runner.find(params[:id])
    end

    def user_params
        params.require(:user_attributes).permit(:username, :password, :password_confirmation)
    end

    def runner_params
        params.require(:runner).permit(:name, :age, :shoe_size, :password, :password_confirmation)
    end
end

app/helpers/runners_helper.rb
module RunnersHelper
end

app/views/runners/_runner_form.html.erb
<% if @errors %>
    <div class="error-messages">
        <% @errors.each do |msg| %>
            <div class="error-message"><%= msg %></div>
        <% end %>
    </div>
<% end %>
<%= bootstrap_form_for @runner do |f| %>
<%= fields_for :user_attributes do |u| %>
    <div class="form-group">
        <%= u.label :username, class: 'required' %>
        <%= u.text_field :username, class: 'form-control' %>
        <%= u.label :password, class: 'required' %>
        <%= u.password_field :password, class: 'form-control' %>
        <%= u.label 'Confirm password', class: 'required' %>
        <%= u.password_field :password_confirmation, class: 'form-control' %>
    </div>
<% end %>
<%= f.text_field :name %>
<%= f.number_field :age %>
<%= f.collection_select :shoe_size, (5.0..14.0).step(0.5), :to_f, :to_f  %>
<%= f.submit %>
<% end %>

app/views/runners/_shoe_deck.html.erb
<div class="card-deck mx-auto">
    <% @runner.runner_shoes.each do |runner_shoe| %>
        <div class="card mx-auto" style="margin-bottom: 15px; margin-top: 15px; max-width: 15rem; min-width: 15rem">
            <% if runner_shoe.shoe.avatar.attachment %>
                <img src=<%= url_for(runner_shoe.shoe.avatar) %> width=238 height=190 class="card-img-top" alt="...">
            <% else %>
                <img src="https://www.famousfootwear.com/productimages/shoes_ib95364.jpg?trim.threshold=105&width=630&height=480&paddingWidth=60" class="card-img-top" alt="...">
            <% end %>
            <%= link_to runner_shoe.brand_with_name, runner_shoe_path(runner_shoe), class: "btn btn-dark" %>
            <div class="card-body">
                <p class="card-text">
                    <ul>
                        <li>Runs: <%= runner_shoe.runs.count %></li>
                        <li>Miles: <%= runner_shoe.get_miles %></li>
                    </ul>
                </p>
            </div>
        </div>
    <% end %>
</div>

app/views/runners/edit.html.erb
<h1>Edit <%= @runner.name %></h1>

<%= render partial: 'runner_form' %>

app/views/runners/index.html.erb
<h1>Runners:</h1>
<ul>
<% @runners.each do |runner| %>
<li><%= link_to runner.name, runner_path(runner) %></li>
<% end %>
</ul>

app/views/runners/my_runs.html.erb
<h1><%= "#{@runner.name}'s Runs:" %></h1>

<ul>
<% @runner.sort_runs.each do |run| %>
<li><%=link_to run.location_date_distance, run_path(run) %></li>
<% end %>
</ul>

app/views/runners/my_shoes.html.erb
<h1><%= "#{@runner.name}'s Shoes:" %></h1>

<%= render partial: 'shoe_deck' %>

app/views/runners/new.html.erb
<h1>Signup Page</h1>

<%= bootstrap_form_for @runner do |f| %>
<%= f.text_field :name %><br>
<%= f.number_field :age %><br>
<%= f.number_field :height %><br>
<%= f.number_field :weight %><br>
<%= f.number_field :shoe_size, min:1, step:0.5 %><br>
<%= f.submit %>
<% end %>

app/views/runners/show.html.erb
<h1>Your Profile</h1>

<h2>Stats:</h2>
<ul>
<li><%= "Runs: #{@runner.total_runs}" %></li>
<li><%= "Total Miles: #{@runner.get_miles}" %>
</ul>

<h2><%= link_to "Runs:", my_runs_path(@runner)%></h2>
<% if @runner.runs.empty? %>
<p>You haven't added any runs yet. <%= link_to "Click here", new_run_path(@runner) %> to add a run.</p>
<% end %>
<ul>
<% @runner.sort_runs.first(5).each do |run| %>
<li><%=link_to run.location_date_distance, run_path(run) %></li>
<% end %>
</ul>

<h2>Shoes:</h2>
<% if @runner.runner_shoes.empty? %>
<p>You haven't added any shoes yet. <%=link_to "Click here", new_runner_shoe_path %> to add a pair.</p>
<% end %>

<%= render partial: 'shoe_deck' %>

<div>
    <h5>Delete profile</h5>
    <%= link_to 'Click here to delete profile', runner_path(@runner), method: :delete, data: {confirm: "Are you sure?" } %>
</div>