config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: [:show, :new, :create, :destroy]
  resources :runs
  resources :brands
  resources :shoes
  resources :runners
  resources :runner_shoes, only: [:show, :new, :create, :destroy]

  root "welcome#homepage"
  get 'terms-and-conditions', to: 'welcome#terms'
  get 'privacy-policy', to: 'welcome#privacy'
  get 'support', to: 'welcome#support'
  get 'about-us', to: 'welcome#about'
  get 'features', to: 'welcome#features'
  get 'contact-us', to: 'welcome#contact'
  get 'what-is-rails-runner', to: 'welcome#whatis'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#process_login'
  get 'logout', to: 'sessions#logout'
  get 'runner/:id/my_runs', to: 'runners#my_runs', as: 'my_runs'
  get 'runner/:id/my_shoes', to: 'runners#my_shoes', as: 'my_shoes'
  get 'brand/:id/targeting', to: 'brands#targeting', as: 'targeting'
  get 'brand/:id/loyal_customers', to: 'brands#loyal_customers', as: 'loyal'

end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :shoes
    has_one :user, as: :profileable

    validates :name, presence: true, length: { minimum: 3 }

    #ANALYTICS
    def due_for_new_pair?
        runner_array = [] 
        self.shoes.each do |shoe|
            shoe.runner_shoes.each do |runner_shoe|
                if runner_shoe.get_miles.to_i > 250
                    runner_array << runner_shoe.runner 
                end 
            end
        end
        return runner_array.uniq
    end

    def loyal_customers
        loyal_customers = []
        Runner.all.each do |runner|
            brand_array = runner.shoes.map {|shoe| shoe.brand}
            if brand_array.count(self) > 1
                loyal_customers << runner
            end
        end
        return loyal_customers
    end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    before_action :set_brand, only: [:show, :edit, :update, :destroy, :new_pair_targets, :loyal_customers]
    
    def index
        @brands = Brand.all
    end

    def show
    end

    def new
        @brand = Brand.new
    end

    def create
        @brand = Brand.new(brand_params)
        @user = User.new(user_params)
        if @user.valid? && @brand.valid?
            @user.save
            @user.profileable = @brand
            @user.save
            session[:user_id] = @user.id
            redirect_to brand_path(@brand)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @brand.update(brand_params)
            redirect_to brand_path(@brand)
        else  
            render :edit
        end
    end

    def destroy
        @brand.user.destroy
        @brand.destroy
        redirect_to root_path
    end

    def targeting
    end

    def loyal_customers 
    end
    

    private

    def user_params
        params.require(:user_attributes).permit(:username, :password, :password_confirmation)
    end

    def brand_params
        params.require(:brand).permit(:name)
    end

    def set_brand
        @brand = Brand.find(params[:id])
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_brand_form.html.erb
<%= bootstrap_form_for @brand do |f| %>
    <%= fields_for :user_attributes do |u| %>
        <div class="form-group">
            <%= u.label :username, class: 'required' %>
            <%= u.text_field :username, class: 'form-control' %>
            <%= u.label :password, class: 'required' %>
            <%= u.password_field :password, class: 'form-control' %>
            <%= u.label 'Confirm password', class: 'required' %>
            <%= u.password_field :password_confirmation, class: 'form-control' %>
        </div>
    <% end %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

app/views/brands/edit.html.erb
<h1>Edit <%= @brand.name %></h1>

<%= render partial: 'brand_form' %>

app/views/brands/index.html.erb
<h1>Brands:</h1>
<ul>
<% @brands.each do |brand| %>
<li><%= link_to brand.name, brand_path(brand) %></li>
<% end %>
</ul>

app/views/brands/loyal_customers.html.erb
<h1>Your Loyal Customers</h1>

<p>These users have two or more pairs of your shoes!</p>

<ul>
<% @brand.loyal_customers.each do |customer|  %>
<li><%= customer.name %></li>
<% end %>
</ul>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render partial: 'brand_form' %>

app/views/brands/show.html.erb
<h1><%= @brand.name %></h1>

<h2>Shoes:</h2>
<ul>
<% @brand.shoes.each do |shoe| %>
    <li><%= link_to shoe.name, shoe_path(shoe) %></li>
<% end %>
</ul>


<%= link_to "Delete Brand", brand_path(@brand), method: :delete, data: { confirm: "Are you sure?"} %>

app/views/brands/targeting.html.erb
<h1>Prime Ad Targets</h1>
<br><br>
<p>Each of these runners has run over 250 miles on one of your shoes. They are probably due for a new pair!</p>
<ul>
<% current_user.profileable.due_for_new_pair?.each do |runner| %>
<li><%= runner.name  %></li>
<% end %>
</ul>