config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: [:show, :new, :create, :destroy]
  resources :runs
  resources :brands
  resources :shoes
  resources :runners
  resources :runner_shoes, only: [:show, :new, :create, :destroy]

  root "welcome#homepage"
  get 'terms-and-conditions', to: 'welcome#terms'
  get 'privacy-policy', to: 'welcome#privacy'
  get 'support', to: 'welcome#support'
  get 'about-us', to: 'welcome#about'
  get 'features', to: 'welcome#features'
  get 'contact-us', to: 'welcome#contact'
  get 'what-is-rails-runner', to: 'welcome#whatis'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#process_login'
  get 'logout', to: 'sessions#logout'
  get 'runner/:id/my_runs', to: 'runners#my_runs', as: 'my_runs'
  get 'runner/:id/my_shoes', to: 'runners#my_shoes', as: 'my_shoes'
  get 'brand/:id/targeting', to: 'brands#targeting', as: 'targeting'
  get 'brand/:id/loyal_customers', to: 'brands#loyal_customers', as: 'loyal'

end

app/models/shoe.rb
class Shoe < ApplicationRecord
    has_one_attached :avatar
    
    belongs_to :brand
    has_many :runner_shoes
    has_many :runners, through: :runner_shoes

    def brand_with_name
        return "#{self.brand.name} #{self.name}"
    end

    def self.sorted_by_brand
        self.joins(:brand).merge(Brand.order(:name))
    end

    def self.get_all_runs(shoe_id)
        self.select(:'shoes.id', :'runs.runner_id', :'runs.distance').joins(runner_shoes: :runs).where(id: shoe_id)
    end

    def total_runs
        x = Shoe.get_all_runs(self.id).map do |run| 
            run.runner_id
        end.count
    end

    def total_miles
        Shoe.get_all_runs(self.id).map do |run| 
            run.distance
        end.sum
    end

    def average_miles_ran_per_run
        if self.total_runs > 0
            (self.total_miles / self.total_runs).round(2)
        else
            return 0
        end
    end

    def average_miles_ran_per_runner
        if self.total_runs > 0
            return (self.total_miles / self.runners.count).round(2)
        else 
            return 0
        end
    end

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
    before_action :set_shoe, only: [:show, :edit, :update, :destroy]
    
    def index
        @shoes = Shoe.all
    end

    def show
    end

    def new
        @shoe = Shoe.new
    end

    def create
        @shoe = Shoe.new(shoe_params)
        if @shoe.save
            redirect_to shoe_path(@shoe)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @shoe.update(shoe_params)
            redirect_to shoe_path(@shoe)
        else
            render :edit
        end
    end

    def destroy
        @brand = @shoe.brand
        @shoe.destroy
        redirect_to brand_path(@brand)
    end

    private

    def shoe_params
        params.require(:shoe).permit(:brand_id, :name, :price, :year, :avatar)
    end

    def set_shoe
        @shoe = Shoe.find(params[:id])
    end
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/shoes/_shoe_form.html.erb
<%= bootstrap_form_for @shoe do |f| %>
    <% if logged_in_admin? %>
        <%= f.collection_select :brand_id, Brand.all, :id, :name %>
    <% else %>
        <%= f.hidden_field :brand_id, :value => current_user.profileable.id%>
    <% end %>
    <%= f.text_field :name %>
    <%= f.number_field :price %>
    <%= f.number_field :year %>
    <%= f.file_field :avatar %>
    <%= f.submit %>
<% end %>

app/views/shoes/edit.html.erb
<h1>Edit <%= @shoe.name %></h1>

<%= render partial: 'shoe_form' %>

app/views/shoes/index.html.erb
<h1>Shoes:</h1>
<ul>
<% @shoes.sorted_by_brand.each do |shoe| %>
<li><%= link_to shoe.brand_with_name, shoe_path(shoe) %></li>
<% end %>
</ul>

app/views/shoes/new.html.erb
<h1>Add a shoe</h1>

<%= bootstrap_form_for @shoe do |f| %>
    <% if logged_in_admin? %>
        <%= f.collection_select :brand_id, Brand.all, :id, :name %>
    <% else %>
        <%= f.hidden_field :brand_id, :value => current_user.profileable.id%>
    <% end %>
    <%= f.text_field :name %>
    <%= f.number_field :price %>
    <%= f.number_field :year %>
    <%= f.submit %>
<% end %>

app/views/shoes/show.html.erb
<h1><%= @shoe.name %></h1>

<h2>Picture</h2>
<%= image_tag(url_for(@shoe.avatar), width: 238, height: 190) %>

<h2>Details</h2>
<ul>
    <li>Price: <%= @shoe.price %></li>
    <li>Year: <%= @shoe.year %></li>
</ul>

<h2>Analytics</h2>
<ul>
    <li>Number of runners with this shoe: <%= @shoe.runners.count %></li>
    <li>Total number of runs: <%= @shoe.total_runs %></li>
    <li>Total miles ran: <%= @shoe.total_miles %></li>
    <li>Average miles ran per run: <%= @shoe.average_miles_ran_per_run %></li>
    <li>Average miles ran per runner: <%= @shoe.average_miles_ran_per_runner %></li>
</ul>

<%= button_to "Edit Shoe", edit_shoe_path(@shoe), method: "get", class: 'btn btn-outline-dark' %>
<%= button_to "Delete Shoe", shoe_path(@shoe), method: "delete", data: { confirm: "Are you sure?" }, class: 'btn btn-outline-dark' %>